
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.dmaldonado.cliente.compiler;

/** CUP generated class containing symbol constants. */
public class GameParserSym {
  /* terminals */
  public static final int SEMICOLON = 12;
  public static final int PLUS = 15;
  public static final int RPAREN = 11;
  public static final int DIGIT = 13;
  public static final int DECIMAL = 14;
  public static final int UP = 2;
  public static final int ERROR = 20;
  public static final int FLOOR = 9;
  public static final int LPAREN = 10;
  public static final int CEIL = 7;
  public static final int HASH = 8;
  public static final int RIGHT = 5;
  public static final int STRING = 19;
  public static final int LEFT = 4;
  public static final int MULT = 18;
  public static final int EOF = 0;
  public static final int DIV = 16;
  public static final int PUSH = 6;
  public static final int MINUS = 17;
  public static final int error = 1;
  public static final int DOWN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UP",
  "DOWN",
  "LEFT",
  "RIGHT",
  "PUSH",
  "CEIL",
  "HASH",
  "FLOOR",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "DIGIT",
  "DECIMAL",
  "PLUS",
  "DIV",
  "MINUS",
  "MULT",
  "STRING",
  "ERROR"
  };
}

