
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.dmaldonado.cliente.compiler;

/** CUP generated class containing symbol constants. */
public class XMLParserSym {
  /* terminals */
  public static final int TARGET_COLOR = 9;
  public static final int BOX_ON_TARGET_COLOR = 8;
  public static final int QUESTION = 25;
  public static final int HALL_COLOR = 11;
  public static final int DIGIT = 27;
  public static final int GREATER_THAN = 22;
  public static final int SLASH = 24;
  public static final int PLAYER = 19;
  public static final int ERROR = 30;
  public static final int NAME = 2;
  public static final int UNDEFINED_COLOR = 12;
  public static final int BOX_COLOR = 7;
  public static final int PROLOG = 26;
  public static final int STRING = 28;
  public static final int TYPE = 6;
  public static final int BRICK = 20;
  public static final int TARGETS = 18;
  public static final int EOF = 0;
  public static final int LESS_THAN = 23;
  public static final int PLAYER_COLOR = 13;
  public static final int BRICK_COLOR = 10;
  public static final int error = 1;
  public static final int ROWS = 3;
  public static final int COLS = 4;
  public static final int HEXADECIMAL = 29;
  public static final int BOXES = 17;
  public static final int BOARD = 14;
  public static final int HALL = 21;
  public static final int CONFIG = 5;
  public static final int POSY = 16;
  public static final int POSX = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME",
  "ROWS",
  "COLS",
  "CONFIG",
  "TYPE",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "PLAYER_COLOR",
  "BOARD",
  "POSX",
  "POSY",
  "BOXES",
  "TARGETS",
  "PLAYER",
  "BRICK",
  "HALL",
  "GREATER_THAN",
  "LESS_THAN",
  "SLASH",
  "QUESTION",
  "PROLOG",
  "DIGIT",
  "STRING",
  "HEXADECIMAL",
  "ERROR"
  };
}

