
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.java.compiler.model;

import java.util.*;
import java_cup.runtime.*;
import dmaldonado.server.model.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class XMLParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return XMLParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public XMLParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public XMLParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public XMLParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\042\000\002\002\004\000\002\002\003\000\002\006" +
    "\006\000\002\006\005\000\002\011\007\000\002\011\004" +
    "\000\002\003\005\000\002\003\004\000\002\005\006\000" +
    "\002\005\004\000\002\007\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\007\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\010\003\000\002\010\003\000" +
    "\002\010\003\000\002\010\003\000\002\010\003\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\002\001\002\000\004\002\006\001\002\000" +
    "\004\002\000\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\006\002\003\004\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$XMLParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$XMLParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$XMLParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private ArrayList<String> errorList;
    private ArrayList<Token> tokenList;

        public GameParser(GameLexer lex){
            super(lex);
            this.errorList = new ArrayList();
            this.tokenList = new ArrayList();
        }

        @Override
        public void syntax_error(Symbol symbol){
            Token token = (Token) symbol.value;
            report_error("Se encontro un error con el token: "+token.getLexeme()+" en la linea: "+token.getLine()+" en la columna: "+token.getColumn());

            System.out.println(report_error("Se encontro un error con el token: "+token.getLexeme()+" en la linea: "+token.getLine()+" en la columna: "+token.getColumn()));

            errorList.add(String.format(report_error("Se encontro un error con el token: "+token.getLexeme()+" en la linea: "+token.getLine()+" en la columna: "+token.getColumn())));
        }

        private String report_error(String s) {
            return s;
        }

        public ArrayList<Token> getTokenList(){
            return tokenList;
        }

        public ArrayList<String> getErrorList(){
            return errorList;
        }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$XMLParser$actions {
  private final XMLParser parser;

  /** Constructor */
  CUP$XMLParser$actions(XMLParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$XMLParser$do_action_part00000000(
    int                        CUP$XMLParser$act_num,
    java_cup.runtime.lr_parser CUP$XMLParser$parser,
    java.util.Stack            CUP$XMLParser$stack,
    int                        CUP$XMLParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$XMLParser$result;

      /* select the action based on the action number */
      switch (CUP$XMLParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= xml EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		RESULT = start_val;
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$XMLParser$parser.done_parsing();
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // xml ::= element 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("xml",0, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // tag ::= prolog open_tag value closed_tag 
            {
              Object RESULT =null;
		 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("tag",4, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // tag ::= open_tag value closed_tag 
            {
              Object RESULT =null;
		 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("tag",4, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // prolog ::= LESS_THAN QUESTION PROLOG QUESTION GREATER_THAN 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("prolog",7, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // prolog ::= ERROR prolog 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		 syntax_error(e); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("prolog",7, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // open_tag ::= LESS_THAN reserved_words GREATER_THAN 
            {
              Object RESULT =null;
		 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("open_tag",1, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // open_tag ::= ERROR open_tag 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		 syntax_error(e); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("open_tag",1, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // closed_tag ::= LESS_THAN SLASH reserved_words GREATER_THAN 
            {
              Object RESULT =null;
		 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("closed_tag",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // closed_tag ::= ERROR open_tag 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		 syntax_error(e); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("closed_tag",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // value ::= DIGIT 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("value",5, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // value ::= STRING 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("value",5, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // value ::= HEXADECIMAL 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("value",5, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // value ::= BRICK 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("value",5, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // value ::= HALL 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("value",5, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // reserved_words ::= NAME 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // reserved_words ::= ROWS 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // reserved_words ::= COLS 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // reserved_words ::= BRICK_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // reserved_words ::= BOX_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // reserved_words ::= BOX_ON_TARGET_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // reserved_words ::= TARGET_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // reserved_words ::= HALL_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // reserved_words ::= UNDEFINED_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // reserved_words ::= PLAYER_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // reserved_words ::= POSX 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // reserved_words ::= POSY 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // reserved_words ::= TYPE 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // reserved_words ::= BOXES 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // reserved_words ::= PLAYER 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // reserved_words ::= CONFIG 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // reserved_words ::= TARGETS 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // reserved_words ::= BOARD 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // reserved_words ::= TYPE 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("reserved_words",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$XMLParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$XMLParser$do_action(
    int                        CUP$XMLParser$act_num,
    java_cup.runtime.lr_parser CUP$XMLParser$parser,
    java.util.Stack            CUP$XMLParser$stack,
    int                        CUP$XMLParser$top)
    throws java.lang.Exception
    {
              return CUP$XMLParser$do_action_part00000000(
                               CUP$XMLParser$act_num,
                               CUP$XMLParser$parser,
                               CUP$XMLParser$stack,
                               CUP$XMLParser$top);
    }
}

}
