
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dmaldonado.server.compiler;

/** CUP generated class containing symbol constants. */
public class ServerParserSym {
  /* terminals */
  public static final int BRICK_COLOR = 10;
  public static final int LBRACKET = 28;
  public static final int MULT = 35;
  public static final int TARGETS = 18;
  public static final int LPAREN = 30;
  public static final int BOX_COLOR = 7;
  public static final int TARGET_COLOR = 9;
  public static final int ROWS = 3;
  public static final int MINUS = 34;
  public static final int FLOOR = 20;
  public static final int CONFIG = 5;
  public static final int RPAREN = 31;
  public static final int TYPE = 6;
  public static final int BOX_ON_TARGET_COLOR = 8;
  public static final int BOARD = 14;
  public static final int COMMA = 27;
  public static final int DIV = 33;
  public static final int DIGIT = 36;
  public static final int HALL = 23;
  public static final int PLUS = 32;
  public static final int HALL_COLOR = 11;
  public static final int DECIMAL = 39;
  public static final int EOF = 0;
  public static final int BRICK = 22;
  public static final int PLAYER = 19;
  public static final int RBRACKET = 29;
  public static final int error = 1;
  public static final int ERROR = 40;
  public static final int NAME = 2;
  public static final int POSY = 16;
  public static final int POSX = 15;
  public static final int COLS = 4;
  public static final int COLON = 26;
  public static final int LBRACE = 24;
  public static final int BOXES = 17;
  public static final int RBRACE = 25;
  public static final int HEXADECIMAL = 38;
  public static final int CEIL = 21;
  public static final int UNDEFINED_COLOR = 12;
  public static final int PLAYER_COLOR = 13;
  public static final int IDENTIFIER = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME",
  "ROWS",
  "COLS",
  "CONFIG",
  "TYPE",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "PLAYER_COLOR",
  "BOARD",
  "POSX",
  "POSY",
  "BOXES",
  "TARGETS",
  "PLAYER",
  "FLOOR",
  "CEIL",
  "BRICK",
  "HALL",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "DIV",
  "MINUS",
  "MULT",
  "DIGIT",
  "IDENTIFIER",
  "HEXADECIMAL",
  "DECIMAL",
  "ERROR"
  };
}

