
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dmaldonado.server.compiler;

import java.util.*;
import java_cup.runtime.*;
import dmaldonado.server.model.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ServerParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ServerParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public ServerParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ServerParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ServerParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\062\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\004\007\000\002\004\007\000\002\004\004\000" +
    "\002\005\003\000\002\005\005\000\002\005\004\000\002" +
    "\006\005\000\002\007\007\000\002\007\007\000\002\007" +
    "\007\000\002\015\005\000\002\015\007\000\002\015\004" +
    "\000\002\011\003\000\002\011\004\000\002\012\005\000" +
    "\002\012\005\000\002\012\005\000\002\012\005\000\002" +
    "\012\004\000\002\012\005\000\002\012\003\000\002\012" +
    "\003\000\002\012\003\000\002\014\006\000\002\014\006" +
    "\000\002\010\003\000\002\010\003\000\002\010\003\000" +
    "\002\010\003\000\002\010\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\003\000\002\013\003\000\002\013" +
    "\003\000\002\013\003\000\002\013\003\000\002\013\003" +
    "\000\002\013\003\000\002\013\003\000\002\013\003\000" +
    "\002\013\003\000\002\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\142\000\006\032\004\052\005\001\002\000\050\004" +
    "\017\005\031\006\032\007\036\010\024\011\022\012\012" +
    "\013\011\014\030\015\014\016\020\017\027\020\035\021" +
    "\041\022\037\023\034\024\025\025\015\052\016\001\002" +
    "\000\006\032\004\052\005\001\002\000\004\002\007\001" +
    "\002\000\004\002\001\001\002\000\004\002\uffff\001\002" +
    "\000\004\034\uffd6\001\002\000\004\034\uffd7\001\002\000" +
    "\004\033\144\001\002\000\004\034\uffd5\001\002\000\004" +
    "\034\140\001\002\000\042\004\017\005\031\006\032\007" +
    "\036\010\024\011\022\012\012\013\011\014\030\015\014" +
    "\016\020\017\027\021\041\022\037\025\015\052\016\001" +
    "\002\000\004\034\uffdc\001\002\000\004\034\uffd4\001\002" +
    "\000\004\033\ufffc\001\002\000\004\034\uffd8\001\002\000" +
    "\004\033\ufffe\001\002\000\004\034\uffd0\001\002\000\004" +
    "\034\133\001\002\000\006\033\ufff8\035\131\001\002\000" +
    "\004\034\uffd3\001\002\000\004\034\uffd9\001\002\000\004" +
    "\034\uffdb\001\002\000\004\034\uffda\001\002\000\004\034" +
    "\067\001\002\000\004\034\063\001\002\000\004\034\050" +
    "\001\002\000\004\034\042\001\002\000\004\034\uffd1\001" +
    "\002\000\004\033\ufffd\001\002\000\004\034\uffd2\001\002" +
    "\000\004\032\043\001\002\000\036\004\017\005\031\006" +
    "\032\010\024\011\022\012\012\013\011\014\030\015\014" +
    "\016\020\017\027\021\041\022\037\052\045\001\002\000" +
    "\004\033\047\001\002\000\036\004\017\005\031\006\032" +
    "\010\024\011\022\012\012\013\011\014\030\015\014\016" +
    "\020\017\027\021\041\022\037\052\045\001\002\000\004" +
    "\033\ufff6\001\002\000\004\033\ufffb\001\002\000\004\036" +
    "\051\001\002\000\006\032\052\052\053\001\002\000\036" +
    "\004\017\005\031\006\032\010\024\011\022\012\012\013" +
    "\011\014\030\015\014\016\020\017\027\021\041\022\037" +
    "\052\045\001\002\000\006\032\052\052\053\001\002\000" +
    "\004\037\055\001\002\000\004\033\ufff4\001\002\000\004" +
    "\037\uffef\001\002\000\004\033\060\001\002\000\006\035" +
    "\061\037\ufff1\001\002\000\006\032\052\052\053\001\002" +
    "\000\004\037\ufff0\001\002\000\004\036\064\001\002\000" +
    "\006\032\052\052\053\001\002\000\004\037\066\001\002" +
    "\000\004\033\ufff3\001\002\000\030\026\073\027\103\030" +
    "\072\031\100\040\105\044\070\046\075\047\101\050\106" +
    "\051\071\052\074\001\002\000\016\026\073\027\103\040" +
    "\105\044\070\046\075\051\071\001\002\000\020\033\uffe5" +
    "\035\uffe5\041\uffe5\042\uffe5\043\uffe5\044\uffe5\045\uffe5\001" +
    "\002\000\006\033\uffde\035\uffde\001\002\000\004\040\125" +
    "\001\002\000\020\026\073\027\103\040\105\044\070\046" +
    "\075\051\071\052\074\001\002\000\020\033\uffe6\035\uffe6" +
    "\041\uffe6\042\uffe6\043\uffe6\044\uffe6\045\uffe6\001\002\000" +
    "\006\033\uffdf\035\uffdf\001\002\000\020\033\uffe4\035\uffe4" +
    "\041\uffe4\042\uffe4\043\uffe4\044\uffe4\045\uffe4\001\002\000" +
    "\006\033\uffdd\035\uffdd\001\002\000\006\033\uffe1\035\uffe1" +
    "\001\002\000\006\033\ufff5\035\ufff5\001\002\000\004\040" +
    "\121\001\002\000\016\033\uffee\035\uffee\042\112\043\114" +
    "\044\113\045\110\001\002\000\016\026\073\027\103\040" +
    "\105\044\070\046\075\051\071\001\002\000\006\033\uffe0" +
    "\035\uffe0\001\002\000\014\041\111\042\112\043\114\044" +
    "\113\045\110\001\002\000\016\026\073\027\103\040\105" +
    "\044\070\046\075\051\071\001\002\000\020\033\uffe7\035" +
    "\uffe7\041\uffe7\042\uffe7\043\uffe7\044\uffe7\045\uffe7\001\002" +
    "\000\016\026\073\027\103\040\105\044\070\046\075\051" +
    "\071\001\002\000\016\026\073\027\103\040\105\044\070" +
    "\046\075\051\071\001\002\000\016\026\073\027\103\040" +
    "\105\044\070\046\075\051\071\001\002\000\020\033\uffe9" +
    "\035\uffe9\041\uffe9\042\uffe9\043\uffe9\044\uffe9\045\uffe9\001" +
    "\002\000\020\033\uffeb\035\uffeb\041\uffeb\042\uffeb\043\114" +
    "\044\uffeb\045\110\001\002\000\020\033\uffec\035\uffec\041" +
    "\uffec\042\uffec\043\114\044\uffec\045\110\001\002\000\020" +
    "\033\uffea\035\uffea\041\uffea\042\uffea\043\uffea\044\uffea\045" +
    "\uffea\001\002\000\016\026\073\027\103\040\105\044\070" +
    "\046\075\051\071\001\002\000\014\041\123\042\112\043" +
    "\114\044\113\045\110\001\002\000\020\033\uffe2\035\uffe2" +
    "\041\uffe2\042\uffe2\043\uffe2\044\uffe2\045\uffe2\001\002\000" +
    "\006\033\uffed\035\uffed\001\002\000\016\026\073\027\103" +
    "\040\105\044\070\046\075\051\071\001\002\000\014\041" +
    "\127\042\112\043\114\044\113\045\110\001\002\000\020" +
    "\033\uffe3\035\uffe3\041\uffe3\042\uffe3\043\uffe3\044\uffe3\045" +
    "\uffe3\001\002\000\020\033\uffe8\035\uffe8\041\uffe8\042\uffe8" +
    "\043\114\044\uffe8\045\110\001\002\000\036\004\017\005" +
    "\031\006\032\010\024\011\022\012\012\013\011\014\030" +
    "\015\014\016\020\017\027\021\041\022\037\052\045\001" +
    "\002\000\004\033\ufff7\001\002\000\004\036\134\001\002" +
    "\000\006\032\052\052\053\001\002\000\004\037\136\001" +
    "\002\000\004\033\ufff2\001\002\000\004\033\ufff9\001\002" +
    "\000\004\032\141\001\002\000\036\004\017\005\031\006" +
    "\032\010\024\011\022\012\012\013\011\014\030\015\014" +
    "\016\020\017\027\021\041\022\037\052\045\001\002\000" +
    "\004\033\143\001\002\000\004\033\ufffa\001\002\000\004" +
    "\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\142\000\004\002\005\001\001\000\016\003\012\004" +
    "\037\005\022\006\025\007\020\013\032\001\001\000\004" +
    "\002\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\004" +
    "\136\005\045\006\025\013\032\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\005\043\006\025\013\032\001\001\000\002\001\001\000" +
    "\010\005\045\006\025\013\032\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\015\053\001" +
    "\001\000\010\005\056\006\025\013\032\001\001\000\004" +
    "\015\055\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\061\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\015\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\010\101\011\075\012\103\014\076\001\001\000" +
    "\006\012\127\014\076\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\011\123\012\103\014" +
    "\076\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\012\106" +
    "\014\076\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\012\117\014\076\001\001\000\002\001\001\000\006" +
    "\012\116\014\076\001\001\000\006\012\115\014\076\001" +
    "\001\000\006\012\114\014\076\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\012\121\014\076\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\012\125\014\076\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\005\131\006\025\013\032\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\015\134\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\005\141\006\025\013\032\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ServerParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ServerParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ServerParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private ArrayList<String> errorList;
    private ArrayList<Token> tokenList;

        public ServerParser(ServerLexer lex){
            super(lex);
            this.errorList = new ArrayList();
            this.tokenList = new ArrayList();
        }

        @Override
        public void syntax_error(Symbol symbol){
            Token token = (Token) symbol.value;
            report_error("Se encontro un error con el token: "+token.getLexeme()+" en la linea: "+token.getLine()+" en la columna: "+token.getColumn());

            System.out.println(report_error("Se encontro un error con el token: "+token.getLexeme()+" en la linea: "+token.getLine()+" en la columna: "+token.getColumn()));

            errorList.add(String.format(report_error("Se encontro un error con el token: "+token.getLexeme()+" en la linea: "+token.getLine()+" en la columna: "+token.getColumn())));
        }

        private String report_error(String s) {
            return s;
        }

        public ArrayList<Token> getTokenList(){
            return tokenList;
        }

        public ArrayList<String> getErrorList(){
            return errorList;
        }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ServerParser$actions {
  private final ServerParser parser;

  /** Constructor */
  CUP$ServerParser$actions(ServerParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ServerParser$do_action_part00000000(
    int                        CUP$ServerParser$act_num,
    java_cup.runtime.lr_parser CUP$ServerParser$parser,
    java.util.Stack            CUP$ServerParser$stack,
    int                        CUP$ServerParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ServerParser$result;

      /* select the action based on the action number */
      switch (CUP$ServerParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= map EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).value;
		RESULT = start_val;
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ServerParser$parser.done_parsing();
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // map ::= LBRACE element RBRACE 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("map",0, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // map ::= ERROR map 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("map",0, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // element ::= pair_list 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("element",1, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // element ::= object 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("element",1, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // element ::= array 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("element",1, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // object ::= CONFIG COLON LBRACE pair_list RBRACE 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("object",2, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // object ::= PLAYER COLON LBRACE pair_list RBRACE 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("object",2, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // object ::= ERROR object 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("object",2, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // pair_list ::= pair 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("pair_list",3, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // pair_list ::= pair COMMA pair_list 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("pair_list",3, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // pair_list ::= ERROR pair_list 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("pair_list",3, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // pair ::= reserved_words COLON value 
            {
              Object RESULT =null;
		  
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("pair",4, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // array ::= BOARD COLON LBRACKET array_list RBRACKET 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("array",5, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // array ::= BOXES COLON LBRACKET array_list RBRACKET 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("array",5, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // array ::= TARGETS COLON LBRACKET array_list RBRACKET 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("array",5, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // array_list ::= LBRACE pair_list RBRACE 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("array_list",11, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // array_list ::= LBRACE pair_list RBRACE COMMA array_list 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("array_list",11, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-4)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // array_list ::= ERROR array_list 
            {
              Object RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("array_list",11, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion_block ::= expr 
            {
              Integer RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = e.intValue(); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expresion_block",7, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expresion_block ::= ERROR expresion_block 
            {
              Integer RESULT =null;
		 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expresion_block",7, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= expr PLUS expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = e1 + e2; 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= expr MINUS expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = e1 - e2; 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= expr MULT expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = e1 * e2; 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= expr DIV expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = e1 / e2; 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= MINUS expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = -e1; 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= LPAREN expr RPAREN 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).value;
		 RESULT = e1; 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-2)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= DIGIT 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = Double.valueOf(e.getLexeme()); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= DECIMAL 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = Double.valueOf(e.getLexeme()); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= op 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 RESULT = e; 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // op ::= FLOOR LPAREN expr RPAREN 
            {
              Double RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)).right;
		Token f = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).value;
		 RESULT = Math.floor(e); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("op",10, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // op ::= CEIL LPAREN expr RPAREN 
            {
              Double RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)).right;
		Token c = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-1)).value;
		 RESULT = Math.ceil(e); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("op",10, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.elementAt(CUP$ServerParser$top-3)), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // value ::= IDENTIFIER 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("value",6, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // value ::= HEXADECIMAL 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("value",6, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // value ::= expresion_block 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 
                                                          Token expresionToken = new Token(String.valueOf(e));
                                                          tokenList.add(expresionToken);
                                                          
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("value",6, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // value ::= BRICK 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("value",6, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // value ::= HALL 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("value",6, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // reserved_words ::= NAME 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // reserved_words ::= ROWS 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // reserved_words ::= COLS 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // reserved_words ::= BRICK_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // reserved_words ::= BOX_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // reserved_words ::= BOX_ON_TARGET_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // reserved_words ::= TARGET_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // reserved_words ::= HALL_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // reserved_words ::= UNDEFINED_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // reserved_words ::= PLAYER_COLOR 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // reserved_words ::= POSX 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // reserved_words ::= POSY 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // reserved_words ::= TYPE 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ServerParser$stack.peek()).value;
		 tokenList.add( new Token(e.getLexeme(), e.getLine(), e.getColumn())); 
              CUP$ServerParser$result = parser.getSymbolFactory().newSymbol("reserved_words",9, ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ServerParser$stack.peek()), RESULT);
            }
          return CUP$ServerParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ServerParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ServerParser$do_action(
    int                        CUP$ServerParser$act_num,
    java_cup.runtime.lr_parser CUP$ServerParser$parser,
    java.util.Stack            CUP$ServerParser$stack,
    int                        CUP$ServerParser$top)
    throws java.lang.Exception
    {
              return CUP$ServerParser$do_action_part00000000(
                               CUP$ServerParser$act_num,
                               CUP$ServerParser$parser,
                               CUP$ServerParser$stack,
                               CUP$ServerParser$top);
    }
}

}
