// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: ServerLexer.flex

package dmaldonado.server.compiler;

import dmaldonado.server.compiler.*;
import java_cup.runtime.Symbol;
import java.util.*;
import dmaldonado.server.model.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class ServerLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int QUOTATION_MARK = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\0\2\1\22\0\1\1\1\0\1\2"+
    "\1\3\4\0\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\12\14\1\15\6\0\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\24\1\27"+
    "\1\30\2\24\1\31\2\24\1\32\5\24\1\33\1\34"+
    "\1\24\1\35\1\0\1\36\1\0\1\37\1\0\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\24\1\51\1\52\1\53\1\54\1\55\1\56\1\24"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\24\1\67\1\0\1\70\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\1\1\16"+
    "\1\17\1\20\1\21\1\7\16\1\1\2\2\0\1\7"+
    "\1\0\5\22\1\0\13\22\1\23\2\24\21\22\1\7"+
    "\1\0\1\22\1\25\1\22\1\26\1\22\1\0\2\22"+
    "\1\27\2\22\1\30\1\22\1\31\1\32\1\33\1\22"+
    "\1\34\1\22\1\7\1\0\1\35\1\36\1\37\2\0"+
    "\1\40\2\22\1\0\3\22\2\24\3\0\1\41\1\0"+
    "\1\42\2\22\1\7\6\0\1\43\1\22\6\0\1\22"+
    "\1\44\5\0\1\22\2\0\1\45\4\0\1\46\4\0"+
    "\1\47\1\50\6\0\1\51\3\0\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\162\0\162\0\162\0\162"+
    "\0\344\0\162\0\162\0\162\0\162\0\162\0\162\0\u011d"+
    "\0\162\0\162\0\162\0\162\0\u0156\0\u018f\0\u01c8\0\u0201"+
    "\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e\0\u0357\0\u0390\0\u03c9"+
    "\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591"+
    "\0\u018f\0\u05ca\0\u0603\0\u063c\0\u0675\0\u018f\0\u06ae\0\u06e7"+
    "\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804\0\u083d\0\u0876\0\u08af"+
    "\0\u08e8\0\u051f\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05\0\u0a3e"+
    "\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06"+
    "\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce"+
    "\0\u018f\0\u0e07\0\u018f\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u018f"+
    "\0\u0f24\0\u0f5d\0\u018f\0\u0f96\0\u018f\0\u018f\0\u018f\0\u0fcf"+
    "\0\u018f\0\u1008\0\u1041\0\u107a\0\u018f\0\u018f\0\u018f\0\u10b3"+
    "\0\u10ec\0\u018f\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209\0\u1242"+
    "\0\u127b\0\162\0\u12b4\0\u12ed\0\u1326\0\u018f\0\u135f\0\u1398"+
    "\0\u13d1\0\u140a\0\u127b\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527"+
    "\0\u1560\0\u018f\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6"+
    "\0\u16ef\0\u1728\0\162\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1845"+
    "\0\u187e\0\u18b7\0\u18f0\0\162\0\u1929\0\u1962\0\u199b\0\u19d4"+
    "\0\162\0\u1a0d\0\u1a46\0\u1a7f\0\u1ab8\0\162\0\162\0\u1af1"+
    "\0\u1b2a\0\u1b63\0\u1b9c\0\u1bd5\0\u1c0e\0\162\0\u1c47\0\u1c80"+
    "\0\u1cb9\0\162";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\7\2\3\1\10"+
    "\3\3\1\11\1\12\17\3\1\13\1\14\24\3\1\4"+
    "\3\3\1\15\1\16\1\3\1\4\1\17\1\20\2\3"+
    "\1\21\1\22\1\3\1\23\1\3\1\24\1\25\1\3"+
    "\1\26\1\27\1\30\2\26\1\31\1\26\1\32\7\26"+
    "\2\3\1\33\1\26\1\34\1\35\4\26\1\36\4\26"+
    "\1\37\1\26\1\40\1\41\1\26\1\42\1\43\1\44"+
    "\3\26\2\3\72\0\1\4\61\0\1\4\21\0\1\11"+
    "\70\0\1\45\1\0\6\45\14\0\6\45\35\0\1\46"+
    "\1\0\1\47\1\0\6\50\14\0\6\50\37\0\1\51"+
    "\1\0\17\51\3\0\27\51\16\0\1\51\1\0\14\51"+
    "\1\52\2\51\3\0\27\51\16\0\1\51\1\0\4\51"+
    "\1\53\12\51\3\0\27\51\16\0\1\51\1\0\12\51"+
    "\1\54\4\51\3\0\27\51\16\0\1\51\1\0\1\55"+
    "\16\51\3\0\27\51\20\0\17\56\3\0\27\56\16\0"+
    "\1\51\1\0\17\51\3\0\15\51\1\57\1\51\1\60"+
    "\7\51\16\0\1\51\1\0\17\51\3\0\15\51\1\61"+
    "\11\51\16\0\1\51\1\0\17\51\3\0\1\62\26\51"+
    "\16\0\1\51\1\0\17\51\3\0\1\63\26\51\16\0"+
    "\1\51\1\0\17\51\3\0\12\51\1\64\2\51\1\65"+
    "\11\51\16\0\1\51\1\0\17\51\3\0\15\51\1\66"+
    "\11\51\16\0\1\51\1\0\17\51\3\0\1\67\25\51"+
    "\1\70\16\0\1\51\1\0\17\51\3\0\14\51\1\71"+
    "\12\51\3\0\1\4\12\0\1\51\1\0\17\51\3\0"+
    "\23\51\1\44\3\51\16\0\1\50\1\0\6\50\14\0"+
    "\6\50\37\0\1\72\66\0\1\46\1\0\1\73\1\0"+
    "\6\74\14\0\6\74\37\0\1\74\1\0\6\74\14\0"+
    "\6\74\37\0\1\51\1\0\10\51\1\75\6\51\3\0"+
    "\27\51\16\0\1\51\1\0\10\51\1\76\6\51\3\0"+
    "\27\51\16\0\1\51\1\0\13\51\1\77\3\51\3\0"+
    "\27\51\16\0\1\51\1\0\12\51\1\100\4\51\3\0"+
    "\27\51\16\0\1\51\1\0\17\51\3\0\1\101\24\51"+
    "\1\102\1\51\16\0\1\51\1\0\17\51\3\0\10\51"+
    "\1\103\16\51\16\0\1\51\1\0\17\51\3\0\12\51"+
    "\1\104\1\51\1\105\12\51\16\0\1\51\1\0\17\51"+
    "\3\0\12\51\1\106\14\51\16\0\1\51\1\0\17\51"+
    "\3\0\13\51\1\107\13\51\16\0\1\51\1\0\17\51"+
    "\3\0\1\110\26\51\16\0\1\51\1\0\17\51\3\0"+
    "\20\51\1\111\6\51\16\0\1\51\1\0\17\51\3\0"+
    "\24\51\1\112\2\51\16\0\1\51\1\0\17\51\3\0"+
    "\17\51\1\113\7\51\16\0\1\51\1\0\17\51\3\0"+
    "\16\51\1\114\10\51\16\0\1\51\1\0\17\51\3\0"+
    "\3\51\1\115\23\51\14\0\1\46\1\0\1\116\1\0"+
    "\6\117\14\0\6\117\37\0\1\117\1\0\6\117\14\0"+
    "\6\117\37\0\1\51\1\0\2\51\1\120\14\51\3\0"+
    "\27\51\16\0\1\51\1\0\12\51\1\121\4\51\3\0"+
    "\27\51\16\0\1\51\1\0\13\51\1\122\3\51\3\0"+
    "\27\51\16\0\1\51\1\0\12\51\1\123\4\51\3\0"+
    "\27\51\16\0\1\51\1\0\17\51\3\0\17\51\1\124"+
    "\7\51\16\0\1\51\1\0\17\51\2\0\1\125\4\51"+
    "\1\126\22\51\16\0\1\51\1\0\17\51\3\0\2\51"+
    "\1\127\24\51\16\0\1\51\1\0\17\51\3\0\20\51"+
    "\1\130\6\51\16\0\1\51\1\0\17\51\3\0\5\51"+
    "\1\131\21\51\16\0\1\51\1\0\17\51\3\0\12\51"+
    "\1\132\14\51\16\0\1\51\1\0\17\51\3\0\4\51"+
    "\1\133\22\51\16\0\1\51\1\0\17\51\3\0\26\51"+
    "\1\134\16\0\1\51\1\0\15\51\1\135\1\136\3\0"+
    "\27\51\16\0\1\51\1\0\17\51\3\0\20\51\1\137"+
    "\6\51\16\0\1\51\1\0\17\51\3\0\6\51\1\140"+
    "\20\51\16\0\1\51\1\0\17\51\3\0\4\51\1\141"+
    "\22\51\16\0\1\51\1\0\17\51\3\0\4\51\1\142"+
    "\22\51\14\0\1\46\1\0\1\143\1\0\6\144\14\0"+
    "\6\144\37\0\1\144\1\0\6\144\14\0\6\144\37\0"+
    "\1\51\1\0\11\51\1\145\5\51\3\0\27\51\16\0"+
    "\1\51\1\0\14\51\1\146\2\51\3\0\27\51\16\0"+
    "\1\51\1\0\17\51\3\0\3\51\1\147\23\51\44\0"+
    "\1\150\12\0\1\151\27\0\1\51\1\0\17\51\3\0"+
    "\20\51\1\152\6\51\16\0\1\51\1\0\17\51\3\0"+
    "\11\51\1\153\15\51\16\0\1\51\1\0\17\51\3\0"+
    "\10\51\1\154\16\51\16\0\1\51\1\0\17\51\2\0"+
    "\1\155\27\51\16\0\1\51\1\0\17\51\3\0\4\51"+
    "\1\156\22\51\16\0\1\51\1\0\17\51\3\0\4\51"+
    "\1\157\22\51\16\0\1\51\1\0\17\51\3\0\5\51"+
    "\1\160\21\51\14\0\1\46\1\0\1\161\1\0\6\162"+
    "\14\0\6\162\37\0\1\162\1\0\6\162\14\0\6\162"+
    "\100\0\1\163\67\0\1\164\30\0\1\51\1\0\17\51"+
    "\2\0\1\165\27\51\16\0\1\51\1\0\17\51\3\0"+
    "\6\51\1\166\20\51\44\0\1\167\42\0\1\51\1\0"+
    "\17\51\3\0\17\51\1\170\7\51\16\0\1\51\1\0"+
    "\17\51\3\0\21\51\1\171\5\51\16\0\1\51\1\0"+
    "\17\51\3\0\10\51\1\172\16\51\14\0\1\46\1\0"+
    "\1\173\126\0\1\174\55\0\1\175\73\0\1\176\103\0"+
    "\1\177\27\0\1\51\1\0\17\51\2\0\1\200\27\51"+
    "\16\0\1\51\1\0\17\51\2\0\1\201\20\51\1\202"+
    "\6\51\16\0\1\51\1\0\17\51\3\0\14\51\1\203"+
    "\12\51\57\0\1\204\74\0\1\205\64\0\1\206\65\0"+
    "\1\207\60\0\1\210\70\0\1\211\42\0\1\51\1\0"+
    "\17\51\3\0\4\51\1\212\22\51\61\0\1\213\51\0"+
    "\1\214\102\0\1\215\73\0\1\216\70\0\1\217\70\0"+
    "\1\220\27\0\1\51\1\0\17\51\3\0\3\51\1\221"+
    "\23\51\61\0\1\222\66\0\1\223\72\0\1\224\63\0"+
    "\1\225\70\0\1\226\32\0\1\51\1\0\17\51\2\0"+
    "\1\227\27\51\50\0\1\230\101\0\1\231\66\0\1\232"+
    "\70\0\1\233\55\0\1\234\72\0\1\235\103\0\1\236"+
    "\70\0\1\237\66\0\1\240\74\0\1\241\61\0\1\242"+
    "\55\0\1\243\106\0\1\244\55\0\1\245\105\0\1\246"+
    "\66\0\1\247\65\0\1\250\73\0\1\251\72\0\1\252"+
    "\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7410];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\4\11\1\1\6\11\1\1\4\11"+
    "\20\1\2\0\1\1\1\0\5\1\1\0\40\1\1\0"+
    "\5\1\1\0\16\1\1\0\3\1\2\0\3\1\1\0"+
    "\4\1\1\11\3\0\1\1\1\0\4\1\6\0\2\1"+
    "\6\0\1\1\1\11\5\0\1\1\2\0\1\11\4\0"+
    "\1\11\4\0\2\11\6\0\1\11\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private ArrayList<String>  errorList;  

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, new Token(value.toString(), yyline + 1, yycolumn + 1));
    }

    private Symbol symbol(int type) {
        return new Symbol(type, new Token(null, yyline + 1, yycolumn + 1));
    }

    private void error(String lexeme){
        errorList.add(String.format("Error lexico en el texto: , %s, linea %d, columna %d, corrige e intenta de nuevo :)", lexeme, yyline+1, yycolumn+1));
    }

    public ArrayList<String> getErrorList(){
        return errorList;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  ServerLexer(java.io.Reader in) {
      errorList = new ArrayList();    
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(ServerParserSym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error(yytext()); return symbol(ServerParserSym.ERROR, yytext());
            }
            // fall through
          case 43: break;
          case 2:
            { /*ignore*/
            }
            // fall through
          case 44: break;
          case 3:
            { yybegin(QUOTATION_MARK);
            }
            // fall through
          case 45: break;
          case 4:
            { return symbol(ServerParserSym.LPAREN, yytext());
            }
            // fall through
          case 46: break;
          case 5:
            { return symbol(ServerParserSym.RPAREN, yytext());
            }
            // fall through
          case 47: break;
          case 6:
            { return symbol(ServerParserSym.COMMA, yytext());
            }
            // fall through
          case 48: break;
          case 7:
            { return symbol(ServerParserSym.DIGIT, yytext());
            }
            // fall through
          case 49: break;
          case 8:
            { return symbol(ServerParserSym.COLON, yytext());
            }
            // fall through
          case 50: break;
          case 9:
            { return symbol(ServerParserSym.LBRACKET, yytext());
            }
            // fall through
          case 51: break;
          case 10:
            { return symbol(ServerParserSym.RBRACKET, yytext());
            }
            // fall through
          case 52: break;
          case 11:
            { return symbol(ServerParserSym.LBRACE, yytext());
            }
            // fall through
          case 53: break;
          case 12:
            { return symbol(ServerParserSym.RBRACE, yytext());
            }
            // fall through
          case 54: break;
          case 13:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 55: break;
          case 14:
            { return symbol(ServerParserSym.MULT, yytext());
            }
            // fall through
          case 56: break;
          case 15:
            { return symbol(ServerParserSym.PLUS, yytext());
            }
            // fall through
          case 57: break;
          case 16:
            { return symbol(ServerParserSym.MINUS, yytext());
            }
            // fall through
          case 58: break;
          case 17:
            { return symbol(ServerParserSym.DIV, yytext());
            }
            // fall through
          case 59: break;
          case 18:
            { return symbol(ServerParserSym.IDENTIFIER, yytext());
            }
            // fall through
          case 60: break;
          case 19:
            { return symbol(ServerParserSym.DECIMAL, yytext());
            }
            // fall through
          case 61: break;
          case 20:
            { return symbol(ServerParserSym.HEXADECIMAL, yytext());
            }
            // fall through
          case 62: break;
          case 21:
            { return symbol(ServerParserSym.CEIL, yytext());
            }
            // fall through
          case 63: break;
          case 22:
            { return symbol(ServerParserSym.HALL, yytext());
            }
            // fall through
          case 64: break;
          case 23:
            { return symbol(ServerParserSym.COLS, yytext());
            }
            // fall through
          case 65: break;
          case 24:
            { return symbol(ServerParserSym.NAME, yytext());
            }
            // fall through
          case 66: break;
          case 25:
            { return symbol(ServerParserSym.POSX, yytext());
            }
            // fall through
          case 67: break;
          case 26:
            { return symbol(ServerParserSym.POSY, yytext());
            }
            // fall through
          case 68: break;
          case 27:
            { return symbol(ServerParserSym.ROWS, yytext());
            }
            // fall through
          case 69: break;
          case 28:
            { return symbol(ServerParserSym.TYPE, yytext());
            }
            // fall through
          case 70: break;
          case 29:
            { return symbol(ServerParserSym.BRICK, yytext());
            }
            // fall through
          case 71: break;
          case 30:
            { return symbol(ServerParserSym.FLOOR, yytext());
            }
            // fall through
          case 72: break;
          case 31:
            { return symbol(ServerParserSym.BOARD, yytext());
            }
            // fall through
          case 73: break;
          case 32:
            { return symbol(ServerParserSym.BOXES, yytext());
            }
            // fall through
          case 74: break;
          case 33:
            { return symbol(ServerParserSym.CONFIG, yytext());
            }
            // fall through
          case 75: break;
          case 34:
            { return symbol(ServerParserSym.PLAYER, yytext());
            }
            // fall through
          case 76: break;
          case 35:
            { return symbol(ServerParserSym.TARGETS, yytext());
            }
            // fall through
          case 77: break;
          case 36:
            { return symbol(ServerParserSym.BOX_COLOR, yytext());
            }
            // fall through
          case 78: break;
          case 37:
            { return symbol(ServerParserSym.HALL_COLOR, yytext());
            }
            // fall through
          case 79: break;
          case 38:
            { return symbol(ServerParserSym.BRICK_COLOR, yytext());
            }
            // fall through
          case 80: break;
          case 39:
            { return symbol(ServerParserSym.PLAYER_COLOR, yytext());
            }
            // fall through
          case 81: break;
          case 40:
            { return symbol(ServerParserSym.TARGET_COLOR, yytext());
            }
            // fall through
          case 82: break;
          case 41:
            { return symbol(ServerParserSym.UNDEFINED_COLOR, yytext());
            }
            // fall through
          case 83: break;
          case 42:
            { return symbol(ServerParserSym.BOX_ON_TARGET_COLOR, yytext());
            }
            // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = ServerParserSym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java ServerLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        ServerLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new ServerLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
